### ISSUE TITLE
touchscreen test program, location on released. 

### ISSUE THREAD

**Issue by jgoeders** [byu-cpe/ecen330_student#19]
There’s been several students whose programs are freezing up because of their faulty touchscreen drivers. What’s happening is they call display_get_touched_point() in their touchscreen_get_location(), and it wasn’t caught until this lab. It seems to freeze whenever they call it on release (i.e. there is no more touched point to get). My guess is they’ve been fine up to now since for previous labs, they’ve been calling it on press.
In any case, for future semesters, it would probably be good to update the touchscreen test code so it calls their get_location() function when it reports RELEASED status so this gets caught earlier

**Comment by gslloyd** [comment]
Added a call to touchscreen_get_location() to lab5_touchscreen/main.c when currentState changes to TEST_TOUCH_RELEASED_ST. If the release location is different from the pressed location, a blue circle is displaced at the released location.
